import Foundation
import ApplicationServices
import AppKit
import Carbon
import Combine

final class CaretManager: ObservableObject {
    static let shared = CaretManager()
    
    @Published var hasAccessibility: Bool = false
    private var accessibilityTimer: Timer?
    
    private init() {
        self.hasAccessibility = AXIsProcessTrusted()
    }
    
    /// Checks if Accessibility permission is currently trusted by macOS TCC (FreeFlow lines 1996-1997)
    func isAccessibilityPermissionGranted() -> Bool {
        let trusted = AXIsProcessTrusted()
        DispatchQueue.main.async {
            self.hasAccessibility = trusted
        }
        return trusted
    }
    
    /// FreeFlow exact startAccessibilityPolling (lines 1310-1329 of AppState.swift)
    func startAccessibilityPolling() {
        accessibilityTimer?.invalidate()
        accessibilityTimer = nil
        
        self.hasAccessibility = AXIsProcessTrusted()
        if self.hasAccessibility {
            print("[CaretManager] ✅ Accessibility permission trusted by macOS TCC.")
            return
        }
        
        print("[CaretManager] ⏳ Starting 2s Accessibility polling until user refreshes TCC permission...")
        accessibilityTimer = Timer.scheduledTimer(withTimeInterval: 2.0, repeats: true) { [weak self] _ in
            DispatchQueue.main.async {
                guard let self = self else { return }
                let trusted = AXIsProcessTrusted()
                self.hasAccessibility = trusted
                if trusted {
                    print("[CaretManager] 🎉 Accessibility permission granted! Re-starting hotkey backend...")
                    HotkeyManager.shared.startMonitoring()
                    self.accessibilityTimer?.invalidate()
                    self.accessibilityTimer = nil
                }
            }
        }
    }
    
    func stopAccessibilityPolling() {
        accessibilityTimer?.invalidate()
        accessibilityTimer = nil
    }
    
    /// FreeFlow exact requestAccessibilityPermission (lines 1336-1342 of AppState.swift)
    func requestAccessibilityPermission() {
        let options = [kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String: true] as CFDictionary
        _ = AXIsProcessTrustedWithOptions(options)
    }
    
    /// Replicates FreeFlow's exact writeTranscriptToPasteboard and pasteAtCursorWhenShortcutReleased
    func pasteTextAtCaret(_ text: String) {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        
        let pasteboard = NSPasteboard.general
        
        // Append trailing space if ending with sentence-ending punctuation (FreeFlow lines 3295-3299)
        let textToWrite: String
        if let last = trimmed.last, ".!?".contains(last) {
            textToWrite = trimmed + " "
        } else {
            textToWrite = trimmed
        }
        
        // Declare transient types alongside .string (FreeFlow lines 3313-3333)
        let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        let legacyTransientType = NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")

        pasteboard.declareTypes([
            .string,
            transientType,
            concealedType,
            autoGeneratedType,
            legacyTransientType
        ], owner: nil)

        pasteboard.setString(textToWrite, forType: .string)
        pasteboard.setString("", forType: transientType)
        pasteboard.setString("", forType: concealedType)
        pasteboard.setString("", forType: autoGeneratedType)
        pasteboard.setString("", forType: legacyTransientType)

        print("[CaretManager] Copied to pasteboard: \"\(textToWrite)\". Firing FreeFlow Cmd+V paste...")
        
        // Direct execution matching FreeFlow: always fire pasteAtCursorWhenShortcutReleased
        pasteAtCursorWhenShortcutReleased()
    }
    
    /// FreeFlow's exact performAfterShortcutReleased (lines 3365-3377 of AppState.swift)
    private func performAfterShortcutReleased(attempt: Int = 0, action: @escaping () -> Void) {
        let maxAttempts = 24
        if HotkeyManager.shared.isRightOptionDown && attempt < maxAttempts {
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.025) {
                self.performAfterShortcutReleased(attempt: attempt + 1, action: action)
            }
            return
        }

        DispatchQueue.main.asyncAfter(deadline: .now() + 0.03) {
            action()
        }
    }

    /// FreeFlow's exact pasteAtCursorWhenShortcutReleased (lines 3379-3384 of AppState.swift)
    private func pasteAtCursorWhenShortcutReleased() {
        performAfterShortcutReleased {
            self.pasteAtCursor()
        }
    }

    /// FreeFlow's exact pasteAtCursor implementation (lines 3233-3244 of AppState.swift)
    private func pasteAtCursor() {
        let source = CGEventSource(stateID: .hidSystemState)
        let vKeyCode = keyCodeForCharacter("v") ?? 9

        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: true)
        keyDown?.flags = .maskCommand
        keyDown?.post(tap: .cgSessionEventTap)

        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: false)
        keyUp?.flags = .maskCommand
        keyUp?.post(tap: .cgSessionEventTap)
        
        print("[CaretManager] Posted Cmd+V via .cgSessionEventTap successfully!")
    }
    
    /// FreeFlow's exact keyCodeForCharacter implementation (lines 3246-3272 of AppState.swift)
    private func keyCodeForCharacter(_ character: String) -> CGKeyCode? {
        guard let char = character.lowercased().utf16.first else { return nil }
        let source = TISCopyCurrentKeyboardInputSource().takeRetainedValue()
        guard let layoutDataRef = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else {
            return nil
        }
        let layoutData = unsafeBitCast(layoutDataRef, to: CFData.self) as Data
        return layoutData.withUnsafeBytes { (ptr: UnsafeRawBufferPointer) -> CGKeyCode? in
            guard let layout = ptr.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self) else {
                return nil
            }
            for keyCode in UInt16(0)..<UInt16(128) {
                var chars = [UniChar](repeating: 0, count: 4)
                var charCount = 0
                var deadKeyState: UInt32 = 0
                let status = UCKeyTranslate(
                    layout, keyCode, UInt16(kUCKeyActionDisplay), 0,
                    UInt32(LMGetKbdType()), OptionBits(kUCKeyTranslateNoDeadKeysBit),
                    &deadKeyState, 4, &charCount, &chars
                )
                if status == noErr, charCount > 0, chars[0] == char {
                    return CGKeyCode(keyCode)
                }
            }
            return nil
        }
    }
}
